Repository TNG/next-generation-scrum-poker, pull requests merged in 2023-09, with the labels that each got.

#118 Update dependencies
  .lintstagedrc
  backend/local/dynamo.ts
  backend/local/socket.ts
  backend/onconnect/src/app.ts
  backend/ondisconnect/src/app.ts
  backend/ondisconnect/src/on-disconnect.ts
  backend/rollup.config.ts
  backend/sendmessage/src/app.ts
  backend/sendmessage/src/login-user.ts
  backend/sendmessage/src/remove-user.ts
  backend/shared/actions.ts
  backend/shared/database/addConnectionToGroup.ts
  backend/shared/database/addUserAndGroupToConnection.ts
  backend/shared/database/createConnection.ts
  backend/shared/database/createGroupWithConnection.ts
  backend/shared/database/deleteConnection.ts
  backend/shared/database/getItem.ts
  backend/shared/database/removeConnectionFromGroup.ts
  backend/shared/database/removeConnectionsFromGroup.ts
  backend/shared/database/removeGroupFromConnection.ts
  backend/shared/database/resetGroupVotes.ts
  backend/shared/database/revealGroupVotes.ts
  backend/shared/database/setGroupConnectionVote.ts
  backend/shared/types.d.ts
  e2e/connection-loss.spec.ts
  e2e/pages/card-page.ts
  e2e/pages/login-page.ts
  e2e/pages/results-page.ts
  frontend/index.html
  frontend/src/Components/App/App.test.tsx
  frontend/src/Components/CardSelector/CardSelector.tsx
  frontend/src/Components/ColorModeProvider/ColorModeProvider.tsx
  frontend/src/Components/KickButton/KickButton.tsx
  frontend/src/Components/PieChart/getPieChartVoteData.ts
  frontend/src/Components/RevealButton/RevealButton.tsx
  frontend/src/Components/ScaleSelector/ScaleSelector.test.tsx
  frontend/src/Components/ScaleSelector/ScaleSelector.tsx
  frontend/src/Components/WebSocket/WebSocket.tsx
  frontend/src/helpers/compareVotes.test.ts
  frontend/src/helpers/compareVotes.ts
  frontend/src/test-helpers/renderWithWebSocket.tsx
  frontend/vite.config.ts
  legacy-redirect/index.html
  package-lock.json
  package.json
  shared/cards.ts
  shared/scales.ts
Labels: dependencies

#127 Change wording: Remove instead of kick
  backend/sendmessage/src/remove-user.ts
  e2e/pages/card-page.ts
  e2e/pages/login-page.ts
  e2e/remove-users.spec.ts
  frontend/src/Components/App/App.test.tsx
  frontend/src/Components/RemoveUserButton/RemoveUserButton.module.css
  frontend/src/Components/RemoveUserButton/RemoveUserButton.tsx
  frontend/src/Components/VotingStateDisplay/VotingStateDisplay.tsx
  frontend/src/constants.ts
Labels: bug, enhancement

#120 Bar chart
  .github/workflows/tests.yml
  frontend/index.html
  frontend/src/Components/BarChart/BarChart.css
  frontend/src/Components/BarChart/BarChart.module.css
  frontend/src/Components/BarChart/BarChart.tsx
  frontend/src/Components/BarChart/getChartVoteData.test.ts
  frontend/src/Components/BarChart/getChartVoteData.ts
  frontend/src/Components/PieChart/PieChart.tsx
  frontend/src/Components/PieChart/getPieChartVoteData.test.ts
  frontend/src/Components/PieChart/getPieChartVoteData.ts
  frontend/src/Components/ResultsPage/ResultsPage.module.css
  frontend/src/Components/ResultsPage/ResultsPage.tsx
  package-lock.json
  package.json
Labels: enhancement
